#!/bin/bash
apt-get update -y && apt-get upgrade -y && apt autoclean -y && apt autoremove
apt install figlet
sleep 3
clear
echo "Espere un momento Cargando paquetes!!"
echo "Desing by @MRX470!!"
sleep 5
clear
apt-get install cmake -y
apt-get install screen wget gcc build-essential g++ make -y
wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/badvpn/badvpn-1.999.128.tar.bz2
tar xf badvpn-1.999.128.tar.bz2
cd badvpn-1.999.128/
cmake ~/badvpn-1.999.128 -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1
make install
screen -dmS screen /usr/local/bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1000 --max-connections-for-client 10

sleep 5
echo "Espere por Favor"
clear

echo "BadVPN instalado correctamente!!"
echo "Espere por Favor"
sleep 3
clear


wget https://raw.githubusercontent.com/andresjoya2018/Badvpn/main/activador.sh; chmod +x ./activador.sh; ./activador.sh
sleep 3
figlet BadVPN
echo ""
echo "BadVPN se a Activado Correctamente"
rm /root/badudp
