#!/bin/bash
apt install figlet
echo "Espere un momento Cargando paquetes!!"
echo "Desing by @MRX470!!"
sleep 5
clear
apt-get install cmake -y
apt-get install screen wget gcc build-essential g++ make -y
wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/badvpn/badvpn-1.999.128.tar.bz2
tar xf badvpn-1.999.128.tar.bz2
cd badvpn-1.999.128/
cmake ~/badvpn-1.999.128 -DBUILD_NOTHING_BY_DEFAULT=1 -DBUILD_UDPGW=1
make install
badvpn-udpgw --listen-addr 127.0.0.1:7300 > /dev/null &
rm /root/badudp
sleep 5
clear
figlet BadVPN Mrx470
echo "BadVPN instalado correctamente!!"
echo "Desing by @MRX470"
