#!/bin/bash
clear
wget https://raw.githubusercontent.com/andresjoya2018/Badvpn/main/activador && bash activador
sleep 3
clear
figlet MRX470 BadVPN
echo "============================"
echo "creado por @mrx470"
echo "Espere un momento por favor"
echo "============================"
sleep 2
clear
figlet MRX470 BadVPN
echo "============================"
echo "creado por @mrx470"
echo "Espere un momento por favor"
echo "10%========================="
sleep 2
clear
figlet MRX470 BadVPN
echo "============================"
echo "creado por @mrx470"
echo "Espere un momento por favor"
echo "===20%======================"
sleep 2
clear
figlet MRX470 BadVPN
echo "============================"
echo "creado por @mrx470"
echo "Espere un momento por favor"
echo "======30%==================="
sleep 2
clear
figlet MRX470 BadVPN
echo "============================"
echo "creado por @mrx470"
echo "Espere un momento por favor"
echo "=========40%================"
sleep 2
clear
figlet MRX470 BadVPN
echo "============================"
echo "creado por @mrx470"
echo "Espere un momento por favor"
echo "===========50%=============="
sleep 2
clear
figlet MRX470 BadVPN
echo "============================"
echo "creado por @mrx470"
echo "Espere un momento por favor"
echo "==============60%==========="
sleep 2
clear
figlet MRX470 BadVPN
echo "============================"
echo "creado por @mrx470"
echo "Espere un momento por favor"
echo "=================70%========"
sleep 2
clear
figlet MRX470 BadVPN
echo "============================"
echo "creado por @mrx470"
echo "Espere un momento por favor"
echo "====================80%====="
sleep 2
clear
figlet MRX470 BadVPN
echo "============================"
echo "creado por @mrx470"
echo "Espere un momento por favor"
echo "======================90%==="
sleep 2
clear
figlet MRX470 BadVPN
echo "============================"
echo "creado por @mrx470"
echo "Espere un momento por favor"
echo "========================100%"
sleep 2
clear
figlet MRX470 BadVPN
echo "============================"
echo "creado por @mrx470"
echo "BadVPN Iniciado Con Exito"

